### ISSUE TITLE
Where is Android version?

### ISSUE THREAD

**Issue by e1sep0** [jasonelle/jasonelle#1]

**Comment by clsource** [comment]
Hello. Thanks for asking 👍 

If you need an android version you can go with the V2 of the framework
although unsuported sadly.

https://github.com/jasonelle-archive/jasonette-android

Version 3 of Android is not on the plans yet, because is best to stick with iOS for the moment.
Maybe in the future we could hire an Android expert, but for now only iOS.

💯

**Comment by e1sep0** [comment]
Thank you =)
